# Generated by Django 5.2.6 on 2026-02-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emp_id', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('basic_salary', models.FloatField()),
                ('hra_percent', models.FloatField()),
                ('da_percent', models.FloatField()),
                ('other_allowance_percent', models.FloatField()),
                ('esi_percent', models.FloatField()),
                ('pf_percent', models.FloatField()),
            ],
        ),
    ]
